---
title: "Comparison 2020-2021--TidyTransit"
output: html_notebook
---

```{r}
# install.packages("tidytransit")
library(tidytransit)
library(dplyr)
library(ggplot2)
```

Load GTFSs
```{r}
gtfs.dir <- "/home/maita/Nextcloud/Documents/Work/Gap_Map/raw/gtfs"
years <- c(2020, 2021)
names(years) <- years
paths = sapply(years, function(n){file.path(gtfs.dir, as.character(n), paste0(as.character(n), ".zip"))})
gtfs = sapply(paths, read_gtfs)
```
Look at them
```{r}
print("SUMMARIES")
sapply(gtfs, summary)
print("VALIDATIONS")
lapply(gtfs, function(g){attr(g, "validation_result")})
```

Frequencies?
```{r}
gtfs <- sapply(gtfs, set_servicepattern)
```


```{r}
servicepatternCalendarViz <- function(gtfs){
  trips_servicepattern = left_join(select(gtfs$trips, trip_id, service_id), gtfs$.$servicepatterns, by = "service_id")
  trip_dates = left_join(gtfs$.$dates_servicepatterns, trips_servicepattern, by = "servicepattern_id")
  
  trip_dates_count = trip_dates %>% group_by(date) %>% summarise(count = dplyr::n()) 
  trip_dates_count$weekday <- lubridate::wday(trip_dates_count$date, label = T, abbr = T, week_start = 7)
  trip_dates_count$day_of_month <- lubridate::day(trip_dates_count$date)
  trip_dates_count$first_day_of_month <- lubridate::wday(trip_dates_count$date - trip_dates_count$day_of_month,  week_start = 7)
  trip_dates_count$week_of_month <- ceiling((trip_dates_count$day_of_month - as.numeric(trip_dates_count$weekday) - trip_dates_count$first_day_of_month) / 7)
  trip_dates_count$month <- lubridate::month(trip_dates_count$date, label = T, abbr = F)
  
  ggplot(trip_dates_count, aes(x = weekday, y = -week_of_month)) + theme_bw() +
    geom_tile(aes(fill = count, colour = "grey50")) +
    geom_text(aes(label = day_of_month), size = 3, colour = "grey20") +
    facet_wrap(~month, ncol = 3) +
    scale_fill_gradient(low = "cornsilk1", high = "DarkOrange", na.value="white")+
      scale_color_manual(guide = F, values = "grey50") +
    theme(axis.text.y = element_blank(), axis.ticks.y = element_blank()) +
    theme(panel.grid = element_blank()) +
    labs(x = NULL, y = NULL, fill = "# trips") +
    coord_fixed()
}
lapply(gtfs, servicepatternCalendarViz)
servicepatternCalendarViz(gtfs$`2020`)
servicepatternCalendarViz(gtfs$`2021`)
```

